language: objective-c
osx_image: xcode8.2
before_install:
  - rvm use $RVM_RUBY_VERSION
  - gem install slather
script:
  - set -o pipefail
  - xcodebuild -destination "OS=10.2,name=iPhone 7 Plus" -scheme "Koara iOS" test
after_success:
  - slather

