language: objective-c
osx_image: xcode8.2
before_install:
  - rvm use $RVM_RUBY_VERSION
  - gem install slather
script:
  - set -o pipefail
  - xcodebuild test -scheme "Koara iOS" -destination "platform=iOS Simulator,name=iPhone 6"
after_success:
  - slather

