language: objective-c
osx_image: xcode8.2
before_install:
  - rvm use $RVM_RUBY_VERSION
  - gem install slather
script:
  - set -o pipefail
  - xcodebuild -version
  - xcodebuild -showsdks
  - xcodebuild -workspace "Koara.xcworkspace" -destination "OS=10.0,name=iPhone 7 Plus" -sdk="iphonesimulator10.2" -scheme "Koara iOS" test
after_success:
  - slather

