language: objective-c
osx_image: xcode8
before_install:
  - rvm use $RVM_RUBY_VERSION
install:
  - bundle install --without=documentation --path ../travis_bundle_dir
script:
  - xcodebuild test -scheme "Koara iOS" -destination "platform=iOS Simulator,name=iPhone 6"
after_success:
  - slather