language: objective-c
osx_image: xcode8
script:
  - xcodebuild -workspace "Koara.xcworkspace" -scheme "Koara iOS" -sdk "iphonesimulator10.0" -destination "OS=10.0,name=iPhone 7 Plus" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test;