language: objective-c
osx_image: xcode8.2
before_install:
  - gem install slather
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
script:
  - travis_retry xcodebuild -scheme "Koara iOS" -destination "platform=iOS Simulator,name=iPhone 6" build-for-testing test
after_success:
  - slather