language: objective-c
osx_image: xcode8
matrix:
  - DESTINATION="platform=iOS Simulator,name=iPhone 6"
script:
  # E.g: xcodebuild test -scheme "Koara" -destination "platform=iOS Simulator,name=iPhone 6"
  - xcodebuild test -scheme "Koara" -destination $DESTINATION
