language: objective-c
osx_image: xcode9

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
  matrix:
    - DESTINATION="OS=11.0,name=iPhone X"                               SCHEME="Koara iOS"    RUN_TESTS="YES"   SEND_TO_COVERALLS="YES"
    - DESTINATION="OS=11.0,name=iPhone 8"                               SCHEME="Koara iOS"    RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
    - DESTINATION="OS=10.3.1,name=iPhone 7 Plus"                        SCHEME="Koara iOS"    RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
    - DESTINATION="OS=10.2,name=iPhone 7"                               SCHEME="Koara iOS"    RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
    - DESTINATION="OS=10.1,name=iPhone 6 Plus"                          SCHEME="Koara iOS"    RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
    - DESTINATION="OS=10.0,name=iPhone 6"                               SCHEME="Koara iOS"    RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
    - DESTINATION="OS=9.3,name=iPad Pro (12.9-inch)"                    SCHEME="Koara iOS"    RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
    - DESTINATION="OS=8.1,name=iPad Air"                                SCHEME="Koara iOS"    RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
    - DESTINATION="platform=macOS"                                      SCHEME="Koara macOS"  RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
    - DESTINATION="platform=tvOS Simulator,OS=10.2,name=Apple TV 1080p" SCHEME="Koara tvOS"   RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"

  before_install:
    - gem install slather
script:
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -workspace "Koara.xcworkspace" -scheme "$SCHEME" -destination "$DESTINATION" test;
    else
      travis_retry xcodebuild -workspace "Koara.xcworkspace" -scheme "$SCHEME" -destination "$DESTINATION" build;
    fi
after_success:
  - if [ $SEND_TO_COVERALLS == "YES" ]; then
      echo "Send to coveralls"
      slather
    fi
notifications:
  email: false