language: objective-c
osx_image: xcode8.1
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
  - IOS_SDK=iphonesimulator10.2
  matrix:
   - DESTINATION="OS=10.2,name=iPhone 7 Plus"     SCHEME="Koara iOS"     SDK="$IOS_SDK"     RUN_TESTS="YES" BUILD_EXAMPLE="YES" POD_LINT="YES"
before_install:
  - rvm use $RVM_RUBY_VERSION
  - gem install slather
script:
  - set -o pipefail
  - xcodebuild -showsdks
  - xcodebuild -workspace "Koara.xcworkspace" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test | xcpretty;
after_success:
  - slather

