language: objective-c
osx_image: xcode8.3

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
  matrix:
    - SCHEME="KoaraHtml iOS"      DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPad Air"              RUN_TESTS="YES"   SEND_TO_COVERALLS="YES"
    - SCHEME="KoaraHtml iOS"      DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone 5s"             RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
    - SCHEME="KoaraHtml iOS"      DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPad Air 2"            RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
    - SCHEME="KoaraHtml iOS"      DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone 5"              RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
    - SCHEME="KoaraHtml iOS"      DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone 6"              RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
    - SCHEME="KoaraHtml iOS"      DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPad Pro (12.9-inch)"  RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
    - SCHEME="KoaraHtml iOS"      DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone 6 Plus"         RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
    - SCHEME="KoaraHtml iOS"      DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone SE"             RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
    - SCHEME="KoaraHtml iOS"      DESTINATION="platform=iOS Simulator,OS=10.3.1,name=iPhone 7"              RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
    - SCHEME="KoaraHtml macOS"    DESTINATION="platform=macOS"                                              RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
    - SCHEME="KoaraHtml tvOS"     DESTINATION="platform=tvOS Simulator,OS=10.2,name=Apple TV 1080p"         RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
    - SCHEME="KoaraHtml watchOS"  DESTINATION="platform=watchOS Simulator,OS=3.2,name=Apple Watch - 42mm"   RUN_TESTS="NO"   SEND_TO_COVERALLS="NO"
  before_install:
    - gem install slather

script:
  - if [ $RUN_TESTS == "YES" ]; then
      travis_retry xcodebuild -workspace "Koara.xcworkspace" -scheme "$SCHEME" -destination "$DESTINATION" test;
    else
      travis_retry xcodebuild -workspace "Koara.xcworkspace" -scheme "$SCHEME" -destination "$DESTINATION" build;
    fi

after_success:
  - if [ $SEND_TO_COVERALLS == "YES" ]; then
      echo "Send to coveralls"
      slather
    fi