language: objective-c
osx_image: xcode8.2

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
  matrix:
    - DESTINATION="platform=iOS Simulator,OS=10.0,name=iPhone 7 Plus"
    - DESTINATION="platform=iOS Simulator,OS=9.0,name=iPhone 6"
    - DESTINATION="platform=iOS Simulator,OS=8.1,name=iPhone 4s"
before_install:
  - gem install slather

script:
  - travis_retry xcodebuild -scheme "Koara iOS" -destination "$DESTINATION" build-for-testing test

after_success:
  - slather