language: objective-c
osx_image: xcode8.2

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
  matrix:
    - SCHEME="Koara iOS"      DESTINATION="platform=iOS Simulator,OS=10.2,name=iPhone 7"              RUN_TESTS="YES"   SEND_TO_COVERALLS="NO"
  before_install:
    - gem install slather

script:
  - travis_retry xcodebuild -workspace "Koara.xcworkspace" -scheme "$SCHEME" -destination "$DESTINATION" build;

after_success:
  - if [ $SEND_TO_COVERALLS == "YES" ]; then
      echo "Send to coveralls"
      slather
    fi