language: objective-c
osx_image: xcode8.2
script:
  - xcodebuild -showsdks
  - xcodebuild -workspace "Koara.xcworkspace" -scheme "Koara iOS" -destination "OS=10.2,name=iPhone 7 Plus" -sdk "iphonesimulator10.2" test