language: objective-c
osx_image: xcode8.2
env:
  global:
  - IOS_FRAMEWORK_SCHEME="Koara iOS"
  - IOS_SDK=iphonesimulator10.2
  matrix:
    - DESTINATION="OS=10.2,name=iPhone 7 Plus"     SCHEME="$IOS_FRAMEWORK_SCHEME"     SDK="$IOS_SDK"     RUN_TESTS="YES" POD_LINT="YES"
before_install:
  - rvm use $RVM_RUBY_VERSION
  - gem install slather
script:
  - set -o pipefail
  - if [ $RUN_TESTS == "YES" ]; then
      xcodebuild -workspace "Koara.xcworkspace" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO ENABLE_TESTABILITY=YES test;
    else
      xcodebuild -workspace "Koara.xcworkspace" -scheme "$SCHEME" -sdk "$SDK" -destination "$DESTINATION" -configuration Debug ONLY_ACTIVE_ARCH=NO build;
    fi
after_success:
  - slather