language: objective-c
osx_image: xcode8.2

env:
  global:
    - LANG=en_US.UTF-8
    - LC_ALL=en_US.UTF-8
  matrix:
    - SCHEME="Koara iOS"   DESTINATION="platform=iOS Simulator,id=8188B40E-F57F-4519-AC47-E43D884B9016,OS=10.2  SEND_TO_COVERALLS=NO" # iPhone 7 Plus
    - SCHEME="Koara iOS"   DESTINATION="platform=iOS Simulator,OS=10.1,name=iPhone 7"                           SEND_TO_COVERALLS=NO
    - SCHEME="Koara iOS"   DESTINATION="platform=iOS Simulator,OS=10.0,name=iPhone SE"                          SEND_TO_COVERALLS=NO
    - SCHEME="Koara iOS"   DESTINATION="platform=iOS Simulator,OS=9.3,name=iPhone 6s Plus"                      SEND_TO_COVERALLS=NO
    - SCHEME="Koara iOS"   DESTINATION="platform=iOS Simulator,OS=9.2,name=iPhone 6s"                           SEND_TO_COVERALLS=NO
    - SCHEME="Koara iOS"   DESTINATION="platform=iOS Simulator,OS=9.1,name=iPhone 6 Plus"                       SEND_TO_COVERALLS=NO
    - SCHEME="Koara iOS"   DESTINATION="platform=iOS Simulator,OS=9.0,name=iPhone 6"                            SEND_TO_COVERALLS=NO
    - SCHEME="Koara iOS"   DESTINATION="platform=iOS Simulator,OS=8.3,name=iPhone 5s"                           SEND_TO_COVERALLS=NO
    - SCHEME="Koara iOS"   DESTINATION="platform=iOS Simulator,OS=8.2,name=iPhone 5"                            SEND_TO_COVERALLS=NO
    - SCHEME="Koara iOS"   DESTINATION="platform=iOS Simulator,OS=8.1,name=iPhone 4s"                           SEND_TO_COVERALLS=YES
    - SCHEME="Koara iOS"   DESTINATION="platform=iOS Simulator,OS=8.1,name=iPad 2"                              SEND_TO_COVERALLS=NO
    - SCHEME="Koara iOS"   DESTINATION="platform=iOS Simulator,OS=9.0,name=iPad Air"                            SEND_TO_COVERALLS=NO
    - SCHEME="Koara iOS"   DESTINATION="platform=iOS Simulator,OS=10.0,name=iPad Air 2"                         SEND_TO_COVERALLS=NO
    - SCHEME="Koara macOS" DESTINATION="platform=macOS"                                                         SEND_TO_COVERALLS=NO

before_install:
  - gem install slather

script:
  - travis_retry xcodebuild -scheme "Koara iOS" -destination "$DESTINATION" build-for-testing test

after_success:
  - if [ $SEND_TO_COVERALLS == "YES" ]; then
      echo "Send to coveralls"
      slather
    fi