language: objective-c
osx_image: xcode8.2
xcode_workspace: Koara.xcworkspace
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
script:
  - xcodebuild test -scheme "Koara iOS" -sdk iphonesimulator -destination "name=iPhone SE"