language: objective-c
osx_image: xcode8.2
env:
  global:
  - LC_CTYPE=en_US.UTF-8
  - LANG=en_US.UTF-8
script:
  - xcodebuild test -scheme "Koara iOS" -sdk iphonesimulator -destination "id=8C638466-C2D8-4340-85F0-41ED767B9BEC,OS=8.1,name=iPad 2"